# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ImageEditor', '0005_auto_20160624_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefunction',
            old_name='function_name',
            new_name='class_name',
        ),
    ]
