# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ImageEditor', '0006_auto_20160624_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefunction',
            name='function_type',
            field=models.CharField(
                choices=[('Transform', 'Transform'), ('Tint', 'Color Tint'), ('Adjustment', 'Adjustment'),
                         ('ColorFilter', 'Color Filter'), ('KernelFilter', 'Kernel Filter')], max_length=15),
        ),
    ]
