# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ImageEditor', '0008_colorfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='KernelFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=30)),
            ],
        ),
    ]
