# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ImageEditor', '0009_kernelfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernelfilter',
            name='display_name',
            field=models.CharField(default='Filter', max_length=20),
            preserve_default=False,
        ),
    ]
